import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { IconoirProvider } from "iconoir-react";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-neutral-100 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-50 text-base`}
      >
        <IconoirProvider iconProps={{
          width: "1.25em",
          height: "1.25em",
          strokeWidth: 2,
        }}>
          {children}
        </IconoirProvider>
      </body>
    </html>
  );
}
